### ISSUE TITLE
Examples should be improved

### ISSUE THREAD

**Issue by lindlof** [laverca/laverca#3]
Migrated from SourceForge,
Created: 2013-09-20
Creator: Mikael Lindlöf

The current state of the examples is bad. Most of them contain too much swing nonsense and hard to understand.

**Comment by lindlof** [comment]
Migrated from SourceForge,
Created: 2013-09-21
Creator: Mikael Lindlöf

Examples should definitely have the UI parts and the mobile signature parts clearly separated. Applying the MVC architecture would be nice.
The CLI examples are currently far inferior in terms of amount and functionality to the Swing examples but I don't think that's really an issue.
An idea of web example, originating from Eemeli, is also interesting. I don't think the choice of UI matters much in terms of API documentation. However, this API is bound to be most widely used in web environment. Such examples would, as a side-effect, do a good job demoing the usage of the Laverca API.

**Comment by Hemuu** [comment]
Done.
