### ISSUE TITLE
English translations incomplete

### ISSUE THREAD

**Issue by lindlof** [laverca/laverca#4]
Migrated from SourceForge,
Created: 2013-01-03
Creator: Eemeli Miettinen

Provide translation:

Laverca description 1.2,
Compliance review 1.2

**Comment by lindlof** [comment]
Migrated from SourceForge,
Created: 2013-07-24
Creator: Eemeli Miettinen

Description has changed:
Diff:

--- old
+++ new
@@ -1,5 +1,5 @@
 Provide translation:

-Laverca description 1.0,
-Compliance review 1.0,
+Laverca description 1.2,
+Compliance review 1.2,
 FiCom implementation guideline v2.0

**Comment by Hemuu** [comment]
Added a translated version of the description document. I think this can be closed now.
